language: node_js
node_js: 
  # - stable
  - 7.6.0
  # - 6

install:
  - npm install

script:
  - npm test

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
